- name: update packages
  apt:
    update_cache: yes

- name: install apache2
  apt: 
    name: apache2
    state: present

- name: Create document root directory for virtual hosts
  file:
    path: "{{ item.document_root }}"
    state: directory
  with_items: "{{ apache_vhosts }}"

- name: Create virtual host configuration file
  template:
    src: virtualhostconf.j2
    dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
  notify: Reload Apache
  with_items: "{{ apache_vhosts }}"
