- name: Gather facts
  setup:
- name: update cache
  apt:
    update_cache: yes
- name: Install OpenJDK
  apt:
    name: openjdk-8-jdk
    state: present
- name: Add Elastic APT GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
- name: Add Elastic APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
- name: Insert lines into elasticsearch default file
  blockinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    #marker: "# {mark} ANSIBLE MANAGED BLOCK - Start/End"
    block: |
      http.port: 9200
      network.host: "{{ ansible_eth0.ipv4.address }}"
      discovery.type: single-node
- name: Restart elastic search
  service:
    name: elasticsearch
    state: restarted
- name: Install logstash
  apt:
    name: logstash
    state: present
- name: Install kibana
  apt:
    name: kibana
    state: present
- name: Insert lines into kibana default file
  blockinfile:
    path: /etc/kibana/kibana.yml
    #marker: "# {mark} ANSIBLE MANAGED BLOCK - Start/End"
    block: |
      server.port: 5601
      server.host: "{{ ansible_eth0.ipv4.address }}"
      elasticsearch.hosts: ["http://{{ ansible_eth0.ipv4.address }}:9200"]
- name: Restart kibana service
  service:
    name: kibana
    state: restarted

