---
- name: install java
  apt:
    name: default-jdk
    state: present

- name: Downloading the required url from defaults/main.yml
  get_url:
    url: "{{ req_url }}"
    dest: /opt

- name: creating a directory for maven
  file:
    path: "/opt/maven"
    state: directory

- name: download & unarchive tomcat10 
  unarchive:
    src: "/opt/apache-maven-{{ version }}-bin.tar.gz"
    dest: "/opt/maven"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Add Maven environment variables to /etc/profile.d/maven.sh
  lineinfile:
    path: /etc/profile.d/maven.sh
    line: "{{ item }}"
    create: yes
    mode: "0755"
  loop:
    - "export M2_HOME=/opt/maven # path to your maven folder"
    - "export MAVEN_HOME=/opt/maven # again path to your maven folder"
    - "export PATH=$M2_HOME/bin/:$PATH"

- name: Source maven.sh
  shell: . /etc/profile.d/maven.sh

